---
title: '0513'
author: "tr"
date: "2020/5/13"
output: html_document
---
```{r}
char1 <- c("Wild","Apple","Donald","May","Avocada") 
factor1 <- factor(char1)
library(stringr)
levels(factor1)
```
```{r}
char2 <- c("蔡英文","習近平","Donald Trump","蔡頭") 
factor2 <- factor(char2)
levels(factor2)

sort(
  str_sub(char2,1,1)
)
sort(
  str_sub(char2,2,2)
)
```
```{r}
jsonlite::fromJSON("https://od.cdc.gov.tw/eic/Day_Confirmation_Age_County_Gender_19CoV.json") -> covid19
```

```{r}
# 不可排序類別：性別、縣市、是否境外移入
covid19$縣市 <- 
  factor(covid19$縣市)
covid19$性別 <-
  factor(covid19$性別)
covid19$是否為境外移入 <-
  factor(
    covid19$是否為境外移入
  )
```

```{r}
# 可排序類別資料：年齡層
covid19$年齡層 <-
  factor(
    covid19$年齡層,c("4","5-9","10-14","15-19","20-24","25-29","30-34","35-39","40-44","45-49" ,"50-54","55-59" ,"60-64","65-69","70+"),
    ordered=TRUE
  )

```

```{r}
jsonlite::fromJSON(
  "https://www.dropbox.com/s/jckqryeh5zeat5w/regionPopulation.json?dl=1"
) -> population
unlist(population) -> population

```
```{r}
newLevels <- names(population)
newLevels
```

```{r}
table(covid19$縣市)
```


