---
title: "Untitled"
author: "tr"
date: "2020/6/3"
output: html_document
---
```{r}
# p=1.2的需求量
p=1.2
qd <- 10-5*p # 小心是5*p, 不能寫5p
# p=1.3的需求量
p=1.3
qd <- 10-5*p
# p=1.4的需求量
p=1.4
qd <- 10-5*p
```

```{r}
demand <- # 創造一個物件叫demand
  function(p){
    q_d <- 10-5*p 
  }
# p=1.2的需求量
demand(p=1.2) 
demand
# p=1.3的需求量
demand(1.3)
# p=1.4的需求量
demand(1.4)
demand(1.2) -> q_d1.2 # 相當於
q_d1.2
remove(q_d1.2)
```

```{r}
sup <- 
  function(p){qs=0+2*p }
```

```{r}
#library(lubridate)
```


```{r}
dateInput <- today()
```


```{r}
locationInput <- "新北市"
```

```{r}
jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

```{r}
# 找出符合地點的天氣資訊：weatherAtLocation
(weather_next36hours$cwbopendata$dataset$location$locationName == locationInput) -> pick_location # 可挑出locationInput的「要/不要」向量
pick_location
weather_next36hours$cwbopendata$dataset$location$weatherElement[pick_location][[1]] -> weatherAtLocation
$# 在weatherAtLocation找出符合時間的天氣資訊
weatherAtLocation$elementName[[1]]
(weatherAtLocation$elementName=="MaxT") ->
  pick_MaxT
(weatherAtLocation$elementName=="MinT") ->
  pick_MinT
weatherAtLocation$time[pick_MaxT][[1]]$parameter$parameterName[[1]] -> maxT
weatherAtLocation$time[pick_MinT][[1]]$parameter$parameterName[[1]] -> minT
dateInput
glue::glue("{locationInput} {dateInput} 氣溫，最高{maxT}度，最低{minT}度。")

```

```{r}
askSilly_weather <- function(locationInput,dateInput){
  jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
  
  (weather_next36hours$cwbopendata$dataset$location$locationName == locationInput) -> pick_location
  
  weather_next36hours$cwbopendata$dataset$location$weatherElement[pick_location][[1]] -> weatherAtLocation
  (weatherAtLocation$elementName=="MaxT") ->
    pick_MaxT
  (weatherAtLocation$elementName=="MinT") ->
    pick_MinT
  weatherAtLocation$time[pick_MaxT][[1]]$parameter$parameterName[[1]] -> maxT
  weatherAtLocation$time[pick_MinT][[1]]$parameter$parameterName[[1]] -> minT
  
  glue::glue("{locationInput} {dateInput} 氣溫，最高{maxT}度，最低{minT}度。")
}
askSilly_weather("新北市",today())
```
```{r}
what_time_it_is <- function(tzone){
now() -> nt
whattime <- with_tz(nt, tzone = tzone)
return(whattime)
}
what_time_it_is("Europe/Paris")
```

```{r}
library(codetools)
class(demand)
# 查詢函數formals arguments要求
formals(askSilly_weather)
# 查詢函數主體
body(askSilly_weather)
```
```{r}
learning_topics <- 
  list(
    subject="函數",
    date=lubridate::ymd("2020-06-03"),
    functionsCreated=list(
      demand=demand
      # 等號右邊是呼叫demand_return的定義值，也就是function(...){...}值定義本身。
    )
  )
learning_topics$functionsCreated$demand(1.2)
.Last.value
```

```{r}
typeof(demand)
environment(demand)
# 若函數執行需要Global environment已存在某些物件，查詢需要哪些物件
codetools::findGlobals(demand)
```
```{r}
intercept <- 10
slope <- -5
myDemand <- function(p){
  q_d <- intercept + slope*p
  return(q_d)
}
```

```{r}
environment(demand)
environment(myDemand)
# 移除global environment裡的intercept及slope
rm(intercept)
demand(1.2) # 維持正常運作
.Last.value
myDemand(1.2) # 無法運作
myDemand2 <- function(p, intercept=10, slope=-5){
  q_d <- intercept + slope*p
  return(q_d)
}
```

```{r}
library(glue,lurbidate)
jsonlite::fromJSON("https://data.ntpc.gov.tw/api/datasets/07F7CCB3-ED00-43C4-966D-08E9DAB24E95/json/preview") -> busArrivalForecast # 公車預估到站時間 https://data.ntpc.gov.tw/datasets/07F7CCB3-ED00-43C4-966D-08E9DAB24E95

jsonlite::fromJSON("https://data.ntpc.gov.tw/api/datasets/0EE4E6BF-CEE6-4EC8-8FE1-71F544015127/json/preview") -> busRoutes # 公車路線清單 https://data.ntpc.gov.tw/datasets/0EE4E6BF-CEE6-4EC8-8FE1-71F544015127

jsonlite::fromJSON("https://data.ntpc.gov.tw/api/datasets/34B402A8-53D9-483D-9406-24A682C2D6DC/json/preview") -> busStopsInfo # 公車站位資訊 https://data.ntpc.gov.tw/datasets/34B402A8-53D9-483D-9406-24A682C2D6DC
```
```{r}
rout <- 886
arrive <- function(route,loc)
{
  busRoutes$nameZh=="route" -> route2
  busStopsInfo$nameZh=="loc" -> loc2
  names(route2) -> nr
  
}
```
```{r}
library(magrittr)#pipe
library(rvest) 
library(plyr)
```


```{r}
jsonlite::fromJSON("https://tcgbusfs.blob.core.windows.net/blobbus/GetEstiamteTime.json") -> ar
jsonlite::fromJSON("https://data.taipei/api/getDatasetInfo/downloadResource?id=7996eec3-e88a-4abc-b602-42c81932a9f6&rid=a838c175-47e3-483e-bc9e-cd700d229696") -> rout1
jsonlite::fromJSON("https://data.taipei/api/getDatasetInfo/downloadResource?id=48aa5bca-2a4f-4fb7-a658-43cba51d5d56&rid=dfd68d8e-d3b9-44df-b614-8850c103239f") -> stop

```

