---
title: "Untitled"
author: "tr"
date: "2020/4/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(commit)
## R Markdown
```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

```{r}
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(commit)
```
```{r}
fromJSON("https://data.gov.tw/dataset/26722",
         simplifyDataFrame = F) -> newTaipe
```
```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

```{r}
str(taipeiNightMarkets, max.level=1)
str(taipeiNightMarkets[[1]])
str(taipeiNightMarkets$"華西街觀光夜市")
str(taipeiNightMarkets[c(2,1)])
str(taipeiNightMarkets[c(' 西昌街觀光夜市','饒河街觀光夜市')])
```
```{r}
str(taipeiNightMarkets, max.level=1)
str(taipeiNightMarkets[c(T,F,F,F,T,F,F,F,F,F,F,F,F,T)])
```
```{r}
rep(c(F,14)) -> taipeiNightMarkets
print(taipeiNightMarkets)
taipeiNightMarkets[c(1,3,5)] <- TRUE
print(taipeiNightMarkets)
```




```{r}
listExample <- 
  list(
    student="小明",
    `學期` = list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
str(listExample,max.level = 1)
listExample[c(T,F)]
```
```{r}
get <- listExample[['學期']]
str(get,max.level = 3)
```
```{r}
get1 <- listExample['學期']
str(get1,max.level = 3)
```
```{r}
numVector <- c(2,3,6,-1,4,2,6)
select1 <- numVector[c(1,4)]; select1
select2 <- select1[[1]]; select2

# 相當於
numVector[c(1,4)][[1]]
```
```{r}
g <- c('r',"r","r","t","t","r")
g <- factor(g)
levels(g)
```

